# Fichier : docker-compose.yml

secrets:
  mdb_user_password:
    file: ${SECRETS}/mdb_user_password.txt
  mdb_root_password:
    file: ${SECRETS}/mdb_root_password.txt

networks:
  appnet: {} 

volumes: 
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WP_VOLUME}

  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MDB_VOLUME}

services:
  nginx:
    build:
      context: ./srcs/nginx
      args:
        - ${DOMAIN_NAME}
    container_name: nginx
    image: nginx
    networks:
      - ${NETWORK}
    volumes:
      - "wp:/var/www/html"
    ports:
      - "443:443"
    restart: unless-stopped
  
  mariadb:
    build:
      context: ./srcs/mariadb
    container_name: mariadb
    image: mariadb
    environment:
      - MARIADB_PORT
      - MDB_DIR
      - MYSQL_DATABASE
      - MYSQL_ROOT
      - MYSQL_USER
    secrets:
      - mdb_user_password
      - mdb_root_password
    networks:
      - ${NETWORK}
    volumes:
      - "db:/var/lib/mysql"
    expose:
      - "${MARIADB_PORT}"
    restart: unless-stopped

